# Generated by Django 6.0.5 on 2026-05-20 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(db_index=True)),
                ('from_location', models.CharField(blank=True, max_length=255)),
                ('to_location', models.CharField(blank=True, max_length=255)),
                ('truck_number', models.CharField(blank=True, max_length=64)),
                ('trailer_number', models.CharField(blank=True, max_length=64)),
                ('carrier_name', models.CharField(blank=True, max_length=128)),
                ('miles_today', models.PositiveIntegerField(default=0)),
                ('total_mileage', models.PositiveIntegerField(default=0)),
                ('main_office_address', models.CharField(blank=True, max_length=255)),
                ('home_terminal_address', models.CharField(blank=True, max_length=255)),
                ('total_driving_minutes', models.PositiveIntegerField(default=0)),
                ('total_on_duty_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_logs', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-log_date'],
            },
        ),
        migrations.CreateModel(
            name='DutySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper', 'Sleeper'), ('driving', 'Driving'), ('on_duty', 'On Duty')], max_length=16)),
                ('start_minute', models.PositiveIntegerField()),
                ('end_minute', models.PositiveIntegerField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='logs.dailylog')),
            ],
            options={
                'ordering': ['daily_log', 'start_minute'],
            },
        ),
        migrations.AddIndex(
            model_name='dailylog',
            index=models.Index(fields=['user', '-log_date'], name='logs_dailyl_user_id_a35b50_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailylog',
            constraint=models.UniqueConstraint(fields=('user', 'log_date'), name='unique_user_log_date'),
        ),
        migrations.AddIndex(
            model_name='dutysegment',
            index=models.Index(fields=['daily_log', 'start_minute'], name='logs_dutyse_daily_l_4bcfd4_idx'),
        ),
        migrations.AddConstraint(
            model_name='dutysegment',
            constraint=models.CheckConstraint(condition=models.Q(('end_minute__gt', models.F('start_minute'))), name='segment_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='dutysegment',
            constraint=models.CheckConstraint(condition=models.Q(('start_minute__gte', 0), ('end_minute__lte', 1440)), name='segment_within_day'),
        ),
    ]
