# Generated by Django 6.0.5 on 2026-05-20 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('distance_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('driving_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_trip_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fuel_stop_count', models.PositiveIntegerField(blank=True, null=True)),
                ('route_geometry', models.JSONField(blank=True, default=list)),
                ('geocoded', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='trips_trip_user_id_2f4a85_idx')],
            },
        ),
    ]
